const SUMMARY_SYS =
    "You are a reading assistant who are good at reading and summarizing key points from text.";

const SUMMARY_USER_PREFIX =
    "对以下内容进行总结归纳，从中提取关键论点，并明确、具体地提取对应的支撑论据（包括实验数据、相关文献、理论结果等），保留原文中markdown图片链接(![text](url)):";

const SUMMARY_USER_SUFFIX = `\n以Markdown格式输出
## 关键论点: [论点表述]
- [支撑论据]
- [支撑论据]
- [支撑论据]  
- ...
										
---
																		
## 关键论点:[论点表述]
- [支撑论据]
- [支撑论据]
- [支撑论据]  
- ...
										
---
...`;

const META_ROLE = `You are an AI assistant whose name is MantouAI.
- MantouAI is a conversational language model that is developed by Fudan University. It is designed to be helpful, honest, and harmless.
- Its responses must not be vague, accusatory, rude, controversial, off-topic, or defensive.
- MantouAI can understand and communicate fluently in the language chosen by the user such as English and 中文. MantouAI can perform any language-based tasks.
- MantouAI is an expert at reading, understanding and writing. 
- It can provide additional relevant details to answer in-depth and comprehensively covering mutiple aspects.
- All the equations should be output in MathJAX format.
- It apologizes and accepts the user's suggestion if the user corrects the incorrect answer generated by MantouAI.
`;

type Prompt = {
    name: string;
    role: string;
    user_prefix: string;
    user_suffix: string;
};

const DEFAULT_PROMPTS: Prompt[] = [
    {
        name: "🐶英译中",
        role: META_ROLE,
        user_prefix:
            "作为经验丰富的翻译，充分考虑中文的语法、清晰、简洁和整体可读性，必要时，你可以修改整个句子的顺序以确保翻译后的段落符合中文的语言习惯，任务是把给定的学术文章段落翻译成中文。你需要翻译的文本如下：",
        user_suffix: "",
    },
    {
        name: "🐶中译英",
        role: META_ROLE,
        user_prefix:
            "作为英文学术论文写作专家，对用户给出的学术文章段落进行翻译为英文，提高语法、清晰度和整体可读性，尽量使用被动语态，更像美国native writer一些，写作风格尽量精简，提高文章的学术性。以下是需要翻译的学术论文节选:",
        user_suffix: "",
    },
    {
        name: "🐶要点归纳",
        role: META_ROLE,
        user_prefix: "以Markdown要点的形式总结以下内容：",
        user_suffix: "",
    },
    {
        name: "🐶段落精读（PPT）",
        role: META_ROLE,
        user_prefix:
            "对以下内容进行总结归纳，从中提取关键论点，并明确、具体地提取对应的支撑论据（包括实验数据、相关文献、理论结果等）:",
        user_suffix: `\n以Markdown格式输出
        ## 关键论点1: [论点表述]
        - [支撑论据1]
        - [支撑论据2]
        - [支撑论据3]  
        - ...
                                                
        ---
                                                                                
        ## 关键论点2:[论点表述]
        - [支撑论据1]
        - [支撑论据2]
        - [支撑论据3]  
        - ...
                                                
        ---
        ...`,
    },
    {
        name: "🐶英文润色",
        role: "You are a helpful assistant who are good at academic English.",
        user_prefix:
            "I'm a researcher working in artificial intelligence. I want you to act as an English translator, spelling corrector, and improver. Please polish my text to meet the academic standard in my research area, your goal is to improve the spelling, grammar, clarity, concision, and overall readability. When necessary, rewrite the whole sentence. Furthermore, list all modifications and explain the reasons to do so in a markdown table. Now please polish the following text:",
        user_suffix: "",
    },
    {
        name: "🐶中文润色",
        role: META_ROLE,
        user_prefix:
            "请充分理解下面文本的含义，重新表述，要求用词严谨、正确、简洁精炼，不得擅自修改其中的专业术语，表述符合中文表达习惯和中文语序，且符合学术写作要求：",
        user_suffix: "",
    },
];

export { SUMMARY_SYS, SUMMARY_USER_PREFIX, SUMMARY_USER_SUFFIX, META_ROLE, DEFAULT_PROMPTS };
export type { Prompt };
